on:
  pull_request:
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main

name: continuous-integration

jobs:
  nu-tests:
    env:
      NUSHELL_CARGO_TARGET: ci

    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]
        style: [default]
        rust:
          - stable
        include:
          - style: extra
            flags: "--features=extra"
          - style: default
            flags: ""
        exclude:
          - platform: windows-latest
            style: default
          - platform: macos-latest
            style: default

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      # Temporarily disabled; the cache was getting huge (2.6GB compressed) on Windows and causing issues.
      # TODO: investigate why the cache was so big
      # - uses: Swatinem/rust-cache@v1
      #   with:
      #     key: ${{ matrix.style }}v3 # increment this to bust the cache if needed

      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --profile ci --exclude nu_plugin_* ${{ matrix.flags }}
